"""create ai analyses table

Revision ID: 83f8d95ad695
Revises: e9ae4348ca4b
Create Date: 2026-09-17 10:46:51.823251+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f8d95ad695'
down_revision: Union[str, None] = 'e9ae4348ca4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analyses',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('suggested_category_id', sa.Integer(), nullable=True),
    sa.Column('suggested_priority', sa.String(length=20), nullable=True),
    sa.Column('suggested_severity', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_details', sa.Text(), nullable=True),
    sa.Column('missing_information', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('suggested_team_id', sa.Integer(), nullable=True),
    sa.Column('risk_insight', sa.Text(), nullable=True),
    sa.Column('duplicate_cases', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['suggested_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['suggested_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analyses_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analyses_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analyses_id'))
        batch_op.drop_index(batch_op.f('ix_ai_analyses_case_id'))

    op.drop_table('ai_analyses')
    # ### end Alembic commands ###
