"""create case attachments table

Revision ID: e9ae4348ca4b
Revises: f352e98995cc
Create Date: 2026-09-17 10:40:30.377582+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ae4348ca4b'
down_revision: Union[str, None] = 'f352e98995cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_attachments',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public_to_citizen', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_attachments_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_attachments_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_attachments_id'))
        batch_op.drop_index(batch_op.f('ix_case_attachments_case_id'))

    op.drop_table('case_attachments')
    # ### end Alembic commands ###
