"""create_sla_and_escalations_tables

Revision ID: ee1114f193ff
Revises: 83f8d95ad695
Create Date: 2026-09-17 10:59:25.627209+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1114f193ff'
down_revision: Union[str, None] = '83f8d95ad695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_escalations',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('escalated_by_id', sa.Integer(), nullable=True),
    sa.Column('escalated_to_id', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['escalated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['escalated_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_escalations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_escalations_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_escalations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_escalations_status'), ['status'], unique=False)

    op.create_table('case_slas',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('response_target_hours', sa.Integer(), nullable=False),
    sa.Column('resolution_target_hours', sa.Integer(), nullable=False),
    sa.Column('response_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_status', sa.String(length=50), nullable=False),
    sa.Column('resolution_status', sa.String(length=50), nullable=False),
    sa.Column('is_breached', sa.Boolean(), nullable=False),
    sa.Column('breached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warning_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_slas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_slas_case_id'), ['case_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_case_slas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_slas_is_breached'), ['is_breached'], unique=False)

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_escalated', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.create_index(batch_op.f('ix_cases_is_escalated'), ['is_escalated'], unique=False)


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_is_escalated'))
        batch_op.drop_column('is_escalated')

    with op.batch_alter_table('case_slas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_slas_is_breached'))
        batch_op.drop_index(batch_op.f('ix_case_slas_id'))
        batch_op.drop_index(batch_op.f('ix_case_slas_case_id'))

    op.drop_table('case_slas')
    with op.batch_alter_table('case_escalations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_escalations_status'))
        batch_op.drop_index(batch_op.f('ix_case_escalations_id'))
        batch_op.drop_index(batch_op.f('ix_case_escalations_case_id'))

    op.drop_table('case_escalations')
    # ### end Alembic commands ###
