"""create case activities tables

Revision ID: f352e98995cc
Revises: 23242c282426
Create Date: 2026-09-17 10:32:24.193752+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f352e98995cc'
down_revision: Union[str, None] = '23242c282426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_investigations',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('investigator_id', sa.Integer(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('actions_taken', sa.Text(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('evidence_notes', sa.Text(), nullable=True),
    sa.Column('follow_up_requirements', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['investigator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_investigations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_investigations_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_investigations_id'), ['id'], unique=False)

    op.create_table('case_messages',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('is_from_citizen', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_messages_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_messages_id'), ['id'], unique=False)

    op.create_table('case_tasks',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_tasks_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_tasks_status'), ['status'], unique=False)

    op.create_table('internal_notes',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('internal_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_internal_notes_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_internal_notes_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internal_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_internal_notes_id'))
        batch_op.drop_index(batch_op.f('ix_internal_notes_case_id'))

    op.drop_table('internal_notes')
    with op.batch_alter_table('case_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_case_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_case_tasks_case_id'))

    op.drop_table('case_tasks')
    with op.batch_alter_table('case_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_messages_id'))
        batch_op.drop_index(batch_op.f('ix_case_messages_case_id'))

    op.drop_table('case_messages')
    with op.batch_alter_table('case_investigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_investigations_id'))
        batch_op.drop_index(batch_op.f('ix_case_investigations_case_id'))

    op.drop_table('case_investigations')
    # ### end Alembic commands ###
